# name: snake-test CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     concurrency:
#       group: ${{ github.workflow }}-${{ github.ref }}
#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v2
#       with:
#         node-version: '16.13.2'
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build --if-present
#     - run: npm test

#     - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         if: ${{ github.ref == 'refs/heads/main' }}
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./public